steps:
  - name: ":golang:"
    command: ".buildkite/steps/tests.sh"
    plugins:
      - docker#v3.1.0:
          image: "golang:1.19"
          workdir: /go/src/github.com/buildkite/buildkite-agent-scaler

  - wait
  - name: ":lambda:"
    command: .buildkite/steps/build-lambda.sh
    artifact_paths:
      - handler.zip

  - wait
  - label: ":s3:"
    command: ".buildkite/steps/upload-to-s3.sh"
    agents:
      queue: elastic-runners
    plugins:
      - aws-assume-role-with-web-identity:
          role-arn: arn:aws:iam::032379705303:role/pipeline-buildkite-agent-scaler

  - wait
  - name: ":pipeline:"
    command: .buildkite/steps/upload-release-steps.sh
    branches: master
