steps:
  - name: ":golang:"
    key: test
    command: ".buildkite/steps/tests.sh"
    plugins:
      - docker#v3.1.0:
          image: "golang:1.12"
          workdir: /go/src/github.com/buildkite/buildkite-agent-scaler
          environment:
            - GO111MODULE=off

  - name: ":lambda:"
    key: build
    command: .buildkite/steps/build-lambda.sh
    artifact_paths:
      - handler.zip

  - label: ":s3:"
    key: upload
    command: ".buildkite/steps/upload-to-s3.sh"
    agents:
      queue: "deploy"
    depends_on:
      - test
      - build

  - name: ":pipeline:"
    key: release
    command: .buildkite/steps/upload-release-steps.sh
    branches: master
    depends_on:
      - upload


