steps:
  - wait
  - name: ":lambda:"
    command: .buildkite/steps/build-lambda.sh

  - wait
  - label: ":s3:"
    command: ".buildkite/steps/upload-to-s3.sh"
    agents:
      queue: "deploy"

  - wait
  - name: ":pipeline:"
    command: .buildkite/steps/upload-release-steps.sh
    branches: master


