steps:
  - block: ":rocket: Release ${VERSION}?"

  - label: ":s3:"
    command: ".buildkite/steps/release-version.sh"
    branches: master
    agents:
      queue: elastic-runners
    concurrency: 1
    concurrency_group: 'release'

  - wait
  - label: ":github:"
    command: ".buildkite/steps/github-release.sh"
    branches: master
    agents:
      queue: elastic-runners
    concurrency: 1
    concurrency_group: 'release'
    plugins:
      - aws-assume-role-with-web-identity:
          role-arn: arn:aws:iam::445615400570:role/pipeline-buildkite-agent-scaler
      - aws-ssm#v1.0.0:
          parameters:
            GITHUB_RELEASE_ACCESS_TOKEN: /pipelines/buildkite-agent-scaler/GITHUB_RELEASE_ACCESS_TOKEN
      - ecr#v2.0.0:
          login: true
          account-ids: "445615400570"
      - docker#v3.5.0:
          image: "445615400570.dkr.ecr.us-east-1.amazonaws.com/deploytools:2020.03"
          propagate-environment: true
