steps:
  - name: ":linux: amd64"
    command: .buildkite/steps/build-binary.sh linux amd64

  - wait
  - name: ":lambda:"
    command: .buildkite/steps/build-lambda.sh

  - wait
  - name: ":pipeline:"
    command: .buildkite/steps/upload-release-steps.sh


