steps:
  - wait
  - name: ":lambda:"
    command: .buildkite/steps/build-lambda.sh

  - wait
  - label: ":s3:"
    command: ".buildkite/steps/upload-to-s3.sh"
    branches: master
    agents:
      queue: "deploy"
    concurrency: 1
    concurrency_group: 'release_s3'

  - wait
  - name: ":pipeline:"
    command: .buildkite/steps/upload-release-steps.sh


