steps:
  - name: ":golang:"
    key: test
    command: .buildkite/steps/tests.sh
    plugins:
      - docker#v3.1.0:
          image: "golang:1.19"
          workdir: /go/src/github.com/buildkite/buildkite-agent-scaler

  - name: ":hammer: :lambda:"
    key: build
    command: .buildkite/steps/build-lambda.sh
    artifact_paths:
      - handler.zip

  - label: ":lambda: :arrow_right: :package:"
    key: package
    command: .buildkite/steps/sar.sh
    depends_on:
      - test
      - build

  - block: ":package: :arrow_right: :rocket:?"
    key: release
    depends_on:
      - package

  - label: ":package: :arrow_right: :aws:"
    key: publish
    command: .buildkite/steps/publish-package.sh
    depends_on:
      - release
    plugins:
      - aws-assume-role-with-web-identity:
          role-arn: arn:aws:iam::172840064832:role/pipeline-buildkite-agent-scaler-publish
